User account/develop
yshima42/ft_transcendence pull request #141
Opened 2022-12-02 05:45 UTC by hyoshie

### やったこと
以下の機能を実装しました
- 自分のプロフィール上で対戦履歴、統計情報をapiから取ってきて表示できる
- 任意のユーザーのプロフィールを表示できる
- ユーザーのアイコン画像をクリックすると、そのユーザーのプロフィールに遷移する

### やっていないこと
- 既存のコードのリファクタ
- 正確な対戦履歴、統計情報の表示
対戦に関するapiが完成していないので、正確な情報が表示されません。
具体的にはDB上で自分がplayerOneとなる対戦結果しか取得、表示できません。

2022-12-02 07:53 UTC, kohkubo requested changes

2022-12-02 07:53 UTC, kohkubo commented on frontend/src/features/profile/components/matchhistory/GameResultCard.tsx
> +  const { userId, opponentId, score, createdAt, win } = props;
ここは一回のAPIアクセスで解決できそうです

2022-12-02 07:53 UTC, kohkubo commented on frontend/src/features/profile/components/matchhistory/MatchHistoryCard.tsx
> +    const { matchHistory } = useMatchHistory(id);
ここです

2022-12-02 07:53 UTC, kohkubo commented on frontend/src/features/profile/components/StatsCard.tsx
> +  const { gameStats } = useGameStats(id);
hookの戻り値を変えましょう

2022-12-02 07:53 UTC, kohkubo commented on frontend/src/features/profile/hooks/useProfile.tsx
> +  const result = await axios.get<User>('/users/me/profile');
api hookのほう関数を使いしょう

2022-12-02 08:29 UTC, sunix2019 commented on frontend/src/routes/PublicRoutes.tsx
> +      { path: 'users/:id', element: <Profile /> },
URLから直接打ったときに、ローディングが終わらない状態になっていたので、今後解消が必要そうです。

2022-12-02 08:30 UTC, sunix2019 approved these changes
おつかれさまでした！変更ファイル数多くて大変だったと思います。
アバターからプロフィール飛べていいと思います！ありがとうございました！

2022-12-03 03:12 UTC, hyoshie commented on frontend/src/features/profile/components/StatsCard.tsx
> +  const matchNum = winNum + loseNum;
githubでよく使われていたtotalMatch, totalWinsにしました。

2022-12-03 03:24 UTC, hyoshie commented on frontend/src/features/profile/components/StatsCard.tsx
> +  const { gameStats } = useGameStats(id);
hooksをリファクタする段階で対応します。

2022-12-03 03:25 UTC, hyoshie commented on frontend/src/features/profile/hooks/useProfile.tsx
> +  const result = await axios.get<User>('/users/me/profile');
hooksをリファクタする段階で対応します。

2022-12-03 08:03 UTC, hyoshie commented on frontend/src/routes/PublicRoutes.tsx
> +      { path: 'users/:id', element: <Profile /> },
対応しました。

2022-12-04 02:07 UTC, kohkubo approved these changes

2022-12-04 02:08 UTC, kohkubo approved these changes
おっけー

2022-12-04 02:08 UTC, merged