テストを自動では知らせるアクションを追加しました！
yshima42/ft_transcendence pull request #155
Opened 2022-12-05 09:00 UTC by kohkubo

2022-12-05 09:50 UTC, hyoshie approved these changes

2022-12-05 09:50 UTC, hyoshie commented on backend/package.json
> +    "setup:dev": "yarn install && yarn prisma generate && yarn prisma migrate reset -f"
.env.developmentを使わなくしたことを周知したほうがいいと思います。

2022-12-06 02:10 UTC, Masaya-Kamei requested changes

2022-12-06 02:10 UTC, Masaya-Kamei commented on backend/package.json
> +    "setup:dev": "yarn install && yarn prisma generate && yarn prisma migrate reset -f"
migration ファイルなくても、動くようにしたいです！

2022-12-06 02:10 UTC, Masaya-Kamei commented on setup-dev.sh
> +docker-compose -f backend/docker-compose.yml down
docker って立ち上げ直す必要ありますか？

2022-12-06 02:10 UTC, Masaya-Kamei commented on setup-dev.sh
> +yarn --cwd backend install
yarn setup:dev 使いたいかも。

2022-12-06 02:11 UTC, Masaya-Kamei requested changes

2022-12-06 02:11 UTC, Masaya-Kamei commented on start-app.sh
>  yarn --cwd frontend start:dev &
seed はあったほうがいいと思いました。

2022-12-06 04:06 UTC, kohkubo commented on start-app.sh
>  yarn --cwd frontend start:dev &
シードが必要な場合は、setup:devで実行すればいいって考えたんだけど、そのためにコマンドが走り直す待ち時間を削減したいというモチベーションですか？

使い方としては、init_start.shみたいに立て続けに動くことを想定しています。

2022-12-06 05:32 UTC, Masaya-Kamei commented on start-app.sh
>  yarn --cwd frontend start:dev &
そうですね。「seed リセットして立ち上げ直したい」ってとき、setup:dev による待ち時間が長いと思って。
あんまり「seed リセットして立ち上げ直したい」って場面ないのかな？　おまかせします！

2022-12-06 05:39 UTC, kohkubo commented on start-app.sh
>  yarn --cwd frontend start:dev &
その場合は、コマンド直打ちでいいと思いました！

2022-12-06 05:50 UTC, Masaya-Kamei requested changes
細かいかもですが、init_start.sh と backend/setup-dev.sh 、実行権限付与だけお願いします！

2022-12-06 05:55 UTC, kohkubo commented
エンジニア同士のコミュニケーションは細かくいきましょう！
実行権限付与しました。

2022-12-06 06:00 UTC, merged