２要素認証のテーブルを新たに作成する。
yshima42/ft_transcendence pull request #168
Opened 2022-12-07 02:19 UTC by sunix2019

Closes #148

2022-12-12 03:28 UTC, kohkubo commented on backend/src/auth/auth.service.ts
> +    twoFactorAuthState: boolean;
me too

2022-12-12 03:57 UTC, kohkubo requested changes

2022-12-12 03:57 UTC, kohkubo commented on backend/src/auth/auth.service.ts
> +  async getTwoFactorAuthState(authUserId: string): Promise<boolean> {
booleanで返すならis~という命名でお願いします。

2022-12-12 03:57 UTC, kohkubo commented on backend/src/auth/auth.service.ts
> +      throw new BadRequestException('createTwoFactorAuth failed.');
どういうときにエラーが起きる想定でしょうか。
もしパターンが決まっていそうなら、エラーのパターン分けをしてください。こんな感じです。

```ts
    } catch (error) {
      if (error instanceof PrismaClientKnownRequestError) {
        if (error.code === 'P2002') {
          Logger.warn(`createChatRoom: chatRoom is already exists`);
          throw newHttpException(
            'ChatRoom is already exists',
           HttpStatus.CONFLICT
          );
        }
      }
```

2022-12-12 03:57 UTC, kohkubo commented on backend/src/auth/auth.service.ts
> +      throw new BadRequestException('deleteTwoFactorAuth failed.');
データベースに該当がないなら、Requestのエラーなので400番台のエラーを返すようにしてください。

2022-12-12 03:57 UTC, kohkubo commented on backend/src/auth/auth.service.ts
> +      throw new NotFoundException(
これもRequestエラー？

2022-12-12 03:57 UTC, kohkubo commented on frontend/prisma/schema.prisma
> +  authUserId String   @unique
idはuuidですか？だとしたら@db.Uuidを付けてください。

```
  id                     String       @id @default(uuid()) @db.Uuid
```

2022-12-12 03:57 UTC, kohkubo commented on frontend/src/features/auth/routes/TwoFactorAuth.tsx
> +            href={`http://localhost:3000/auth/2fa/validation?oneTimePassword=${token}`}
変数名で数字始まりを避けている言語が多いので、 エンドポイントでも数字始まりは違和感を感じました。
2ch.netもあり、uriにその規定はないので、問題ないとは思いますが他の変数名と揃えることを考えるなら数字始まりは後々めんどくさくなりそうなので、避けたほうがいいです。

2022-12-12 03:57 UTC, kohkubo commented on frontend/src/hooks/api/auth/useTwoFactorAuthCreate.ts
> +  >('/auth/2fa', [['/auth/2fa'], ['/auth/2fa/state']]);
数字始まりのエンドポイント

2022-12-12 03:57 UTC, kohkubo commented on backend/prisma/schema.prisma
> +model TwoFactorAuth {
そもそもなのですが、2要素認証という名前は全体の認証方式を決めるのもなので、QRコードの認証なら、その認証の名前にしないと何の認証をしているのかわからないと思いました。全体的に何を示すのか明示的な名前にしたほうが良いと思います。

2022-12-12 04:36 UTC, sunix2019 commented on backend/prisma/schema.prisma
> +model TwoFactorAuth {
ワンタイムパスワードを使った認証なので、OneTimePasswordAuthに修正しようと思います。

2022-12-12 05:47 UTC, sunix2019 commented on frontend/src/features/auth/routes/TwoFactorAuth.tsx
> +            href={`http://localhost:3000/auth/2fa/validation?oneTimePassword=${token}`}
2fa->otpに修正しました。

2022-12-12 06:42 UTC, sunix2019 commented on backend/src/auth/auth.service.ts
> +      throw new BadRequestException('createTwoFactorAuth failed.');
考えていたのは、すでに登録していた場合のエラーだったので、提案していただいたものに修正しました。

2022-12-12 06:42 UTC, sunix2019 commented on backend/src/auth/auth.service.ts
> +    twoFactorAuthState: boolean;
isOtpAuthEnabledに修正しました。

2022-12-12 06:45 UTC, sunix2019 commented on backend/src/auth/auth.service.ts
> +      throw new BadRequestException('deleteTwoFactorAuth failed.');
BadRequest（400）ではダメですか？

2022-12-12 06:47 UTC, sunix2019 commented on backend/src/auth/auth.service.ts
> +      throw new NotFoundException(
Requestエラーなので、BadRequest(400)に修正しました。

2022-12-12 06:47 UTC, sunix2019 commented on frontend/src/hooks/api/auth/useTwoFactorAuthCreate.ts
> +  >('/auth/2fa', [['/auth/2fa'], ['/auth/2fa/state']]);
2fa->otpに修正しました。

2022-12-13 01:04 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
>  @Controller('auth')
usersService 使ってなさそうなので削除お願いします！

2022-12-13 01:04 UTC, Masaya-Kamei commented on backend/src/auth/auth.module.ts
>  @Module({
import users  使ってないのであれば、削除お願いします！

2022-12-13 01:08 UTC, Masaya-Kamei commented on backend/src/auth/auth.module.ts
>    exports: [JwtStrategy, JwtAuthGuard],
jwt と同じように、export したほうがいいかも？

2022-12-13 01:10 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
>  @Controller('auth')
削除しました！

2022-12-13 01:13 UTC, sunix2019 commented on backend/src/auth/auth.module.ts
>  @Module({
imports UsersModule削除しました！

2022-12-13 01:16 UTC, sunix2019 commented on backend/src/auth/auth.module.ts
>    exports: [JwtStrategy, JwtAuthGuard],
exportさせました！

2022-12-13 07:15 UTC, kohkubo commented on frontend/src/features/auth/routes/TwoFactorAuth.tsx
> +            href={`http://localhost:3000/auth/2fa/validation?oneTimePassword=${token}`}
良い忘れていました！単語つなぐ場合はハイフンでつないでください！

2022-12-13 07:26 UTC, kohkubo approved these changes

2022-12-13 08:08 UTC, sunix2019 commented on frontend/src/features/auth/routes/TwoFactorAuth.tsx
> +            href={`http://localhost:3000/auth/2fa/validation?oneTimePassword=${token}`}
修正しました！

2022-12-14 03:57 UTC, merged