Game/dev/top
yshima42/ft_transcendence pull request #191
Opened 2022-12-09 01:23 UTC by yshima42

2022-12-09 01:25 UTC, yshima42 commented
roomsの設計ミスがあったのでそれを修正してからmainにマージしたい

2022-12-16 01:28 UTC, sunix2019 commented on backend/src/game/game.object.ts
> +  down: boolean;
up, downもし不要であれば削除お願いします。

2022-12-16 01:38 UTC, Masaya-Kamei requested changes
細かいかもですが、気になった点指摘しました。

2022-12-16 01:38 UTC, Masaya-Kamei commented on backend/src/game/game.gateway.ts
> +// eslint-disable-next-line import/extensions
.eslintrc.json の68行あたりに記載すれば、解決できそう

2022-12-16 01:38 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +export type Ball = {
Ball とdefaultBall 、classにしてコンストラクタで初期してもいいかも。

2022-12-16 01:38 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +export type Paddle = {
Ball と同じ。

2022-12-16 01:38 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +  gameLogic(roomId: string): void {
ここの粒度が大きい気がします。
gameLogic の中身を３関数に分けて、setInterval にいれてもよさそうだと思いました。

2022-12-16 01:38 UTC, Masaya-Kamei commented on frontend/src/config/default.ts
> +export const SOCKET_URL = 'http://localhost:3000';
昨日よしえさんが用意してくれたVITE_WS_BASE_URL 使えば良さそう

2022-12-16 01:38 UTC, Masaya-Kamei commented on frontend/src/features/game/utils/gameContext.ts
> +import { createContext } from 'react';
使ってなそうなので削除してもいいと思いました。

2022-12-16 01:38 UTC, Masaya-Kamei commented on frontend/src/features/game/utils/gameConfig.ts
> +// TODO: これらを設定などで変えられる機能を作る
設定値、front から最初に送って、backのGameRoom クラスに入れれば、back で管理しなくてもよくなるし、フロントで設定も変えれそう？
逆にしてback で管理もできるか。。
コメントなので、後回しでいいです。

2022-12-16 01:38 UTC, Masaya-Kamei commented on backend/src/game/game.module.ts
> +// eslint-disable-next-line import/extensions
ここも.eslintrc.json に書き足せばよさそう

2022-12-16 01:51 UTC, sunix2019 approved these changes
一通りコードと挙動を確認しました！
ゲームの挙動は問題なかったと思います。
追加実装頑張りましょう！！

2022-12-16 04:17 UTC, yshima42 commented on backend/src/game/game.object.ts
> +  gameLogic(roomId: string): void {
こちらmoveBallとcheckFinishに分けてみたのですが、しっくり来なかったのでgameLogicのままにしました。paddleに紐付いていたscoreはplayerに紐づくように修正しました。もうちょっと良い方法見つかればgameLogicの分割検討します。

2022-12-16 04:36 UTC, Masaya-Kamei approved these changes
良いと思います。
お疲れ様でした！！！

2022-12-16 04:36 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +  gameLogic(roomId: string): void {
考えてもらってありがとうございます。
良いと思います！

2022-12-16 04:40 UTC, merged