プロフィール画面にフレンド登録ボタンを表示する。
yshima42/ft_transcendence pull request #207
Opened 2022-12-12 02:32 UTC by sunix2019

2022-12-15 02:28 UTC, kohkubo requested changes

2022-12-15 02:28 UTC, kohkubo commented on frontend/src/types/friend-relation.d.ts
> +  friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
```
export type FriendRelation = 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
```

この書き方ではだめですか？

2022-12-15 02:28 UTC, kohkubo commented on frontend/src/hooks/api/profile/useProfileFriendRequestReject.ts
> +    const result = await axios.delete<RejectFriendRequestInProfileResBody>(
```
const result = await axios.delete<RejectFriendRequestInProfileResBody>(
  `/users/me/friend-requests/incoming/${userId}`
);
```

このように書くように習慣化しておくと、URIの途中に変数が来たときも簡単に書けます。
書き方を統一しましょう。

2022-12-15 02:28 UTC, kohkubo commented on frontend/src/hooks/api/profile/useProfileFriendRequestCancel.ts
> +      '/users/me/friend-requests/' + userId
書き方を統一しましょう

2022-12-15 05:51 UTC, Masaya-Kamei requested changes
細々したとこ、めちゃくちゃ助かります！
確認お願いします！

2022-12-15 05:51 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
>    @Patch('me/friend-requests/incoming')
フレンド申請の承認と拒否でエンドポイントが違っているのが気になります。

2022-12-15 05:51 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +  @Get('me/friend-relation/:id')
良いと思います！
特定のユーザーとのブロックの関係値を返すエンドポイントも作成して使うようにしてくれませんか？
現在、Profile コンポーネントでは、ブロックしてるユーザーすべて取得して、やってる。

2022-12-15 05:51 UTC, Masaya-Kamei commented on backend/src/friend-requests/types/friend-relation.d.ts
> +export type FriendRelation = {
バックのgame/interfaces とフロントのhooks/api/game/useMatchHistory みて、揃えて欲しいです！

2022-12-15 05:51 UTC, Masaya-Kamei commented on backend/src/friend-requests/friend-requests.service.ts
> +    let friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
ここの型、作成したFriendRelation 使って欲しいです。

2022-12-15 05:51 UTC, Masaya-Kamei commented on backend/src/friend-requests/types/friend-relation.d.ts
> +  friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
enum のほうがいい？

2022-12-15 05:51 UTC, Masaya-Kamei commented on frontend/src/hooks/api/generics/useDeleteApi.ts
> +          void queryClient.invalidateQueries(queryKey);
なぜ{} いらないんですか？？
https://tanstack.com/query/v4/docs/guides/invalidations-from-mutations

2022-12-15 05:51 UTC, Masaya-Kamei commented on frontend/src/hooks/api/profile/useProfileFriendRequest.ts
> +import { User } from '@prisma/client';
このuseProfileFriendRequest〜 は、relations ディレクトリにあるものは使えないのですか？

2022-12-15 05:53 UTC, sunix2019 commented on frontend/src/types/friend-relation.d.ts
> +  friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
この書き方に修正しました！

2022-12-15 05:55 UTC, sunix2019 commented on backend/src/friend-requests/friend-requests.service.ts
> +    let friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
修正しました！

2022-12-15 05:59 UTC, Masaya-Kamei commented on backend/src/friend-requests/types/friend-relation.d.ts
> +  friendRelation: 'NONE' | 'ACCEPTED' | 'PENDING' | 'RECOGNITION';
enum 使わない方がいいみたい。
https://typescriptbook.jp/reference/values-types-variables/enum/enum-problems-and-alternatives-to-enums

2022-12-16 02:23 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
>    @Patch('me/friend-requests/incoming')
すみません、今のままで大丈夫です！
POST,PATCH はbody にいれて、DELETE はurl に入れるでいいですね！
申し訳なかったです。

2022-12-16 03:01 UTC, Masaya-Kamei requested changes

2022-12-16 03:01 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/UserInfoCard.tsx
>          {isLoginUser && <ProfileSetting />}
せきぐちさん、書いてないかもだけど、三項演算子のほうがわかりやすいと思います。

2022-12-16 03:37 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +
friend-relations の方が適切だと思いました。
自分が関わるたくさんのフレンド関係から１つを選ぶので。

2022-12-16 03:39 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +  @Get('me/friend-relation/:id')
friend-relations の方が適切だと思いました。
自分が関わるたくさんのフレンド関係から１つを選ぶので。

2022-12-16 04:39 UTC, sunix2019 commented on frontend/src/hooks/api/generics/useDeleteApi.ts
> +          void queryClient.invalidateQueries(queryKey);
現行のものはドキュメントに載っていないので、一行目の方式に直します！

2022-12-16 04:50 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  @Get('me/blocks/:id')
大変わかりやすかったので修正しました！

2022-12-16 04:51 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  @ApiOkResponse({ type: UserEntity, isArray: true })
修正しました！

2022-12-16 05:21 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
>          {isLoginUser && <ProfileSetting />}
修正しました！

2022-12-16 05:27 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  @Get('me/friend-relation/:id')
複数ある関係の中から一つの関係を取得してくるので、単数形のほうが適切かなと僕は思いました。
複数人の中から一人選ぶ関数もgetUsersになってしまうと思います。

2022-12-16 05:36 UTC, sunix2019 commented on frontend/src/features/profile/components/BlockButton.tsx
> +  const queryKeys = [[`/users/me/blocks/${userId}`]];
そのとおりです！修正しました！

2022-12-16 09:46 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +  @Get('me/friend-relation/:id')
複数の「関係」ではなく、複数の「人との関係」です！
「たくさんの人の関係」から、「特定の人との関係」をとる。

2022-12-18 10:18 UTC, sunix2019 commented on frontend/src/hooks/api/relations/useFriendRequest.ts
> +  queryKeys: QueryKey[] = []
別のプルリクで解消させたいと思います。

2022-12-18 10:22 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  @Get('me/friend-relation/:id')
僕の論点がずれてました！friend-relationsに修正しました！

2022-12-18 10:48 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  @ApiOkResponse({ type: UserEntity, isArray: true })
FriendRelationに修正しました！

2022-12-19 01:56 UTC, Masaya-Kamei requested changes
お疲れ様です。
修正お願いします！

2022-12-19 01:56 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <FriendButton otherId={user.id} />
friend-relations とblock-relations 使う位置、統一してほしいです。

2022-12-19 01:56 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <BlockButton userId={user.id} isBlockedUser={isBlockedUser} />
あと、FriendButtonはotherId で、BlockButton はuserId になってるので揃えてください。

2022-12-19 01:56 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +            <GameButton isGamePlaying={false} />
どうせなら、DMButton ほしいかもです。
全員とDM できる場合は、GameButton の横に用意する。
Friend のみの場合は、FriendButton の中で用意する。
全員とフレンドのみどっちでしたっけ？

2022-12-19 02:21 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <BlockButton userId={user.id} isBlockedUser={isBlockedUser} />
userIdにそろえました！

2022-12-19 02:27 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <BlockButton userId={user.id} isBlockedUser={isBlockedUser} />
otherId とか、targetId のほうが適切だと思いました！

2022-12-19 02:36 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <FriendButton otherId={user.id} />
block-relationsの使用位置をBlockButtonに変更して統一しました。

2022-12-19 03:04 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +            <GameButton isGamePlaying={false} />
全員とDMできるようにすることになると思うので、Gameの横にDMボタン設置しました！
ブロックユーザーの場合は非表示にしました。

2022-12-19 03:17 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <FriendButton otherId={user.id} />
friend-relation, block-relationどちらもUserInfoCardで使用するようにしました！

2022-12-19 03:29 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +              <BlockButton userId={user.id} isBlockedUser={isBlockedUser} />
targetIdに修正しました！

2022-12-19 03:41 UTC, Masaya-Kamei requested changes
何度もすみません！

2022-12-19 03:41 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +  ): Promise<boolean> {
{ isBlocked: boolean } か { isUserBlocked: boolean } の方がいいと思いました！

2022-12-19 03:41 UTC, Masaya-Kamei commented on frontend/src/hooks/api/block/useIsBlockedUser.ts
> +export const useIsBlockedUser = (
hooks 名、useBlockRelation で、返り値、isBlockedUser ではなく、isBlocked か、isUserBlocked のほうがわかりやすいと思いました。

2022-12-19 03:42 UTC, Masaya-Kamei commented on backend/src/users/users.controller.ts
> +  ): Promise<boolean> {
全体的に、isBlockedUser わかりにくいかもです。
isUserBlocked とか？

2022-12-19 05:22 UTC, sunix2019 commented on backend/src/users/users.controller.ts
> +  ): Promise<boolean> {
返り値オブジェクトにして、isUserBlockedに修正しました！

2022-12-19 05:31 UTC, sunix2019 commented on frontend/src/hooks/api/block/useIsBlockedUser.ts
> +export const useIsBlockedUser = (
useBlockRelation, isUserBlockedに修正しました！

2022-12-19 05:50 UTC, yshima42 approved these changes

2022-12-19 07:03 UTC, Masaya-Kamei approved these changes

2022-12-19 07:13 UTC, merged