Friendページni
yshima42/ft_transcendence pull request #237
Opened 2022-12-20 10:05 UTC by sunix2019

2022-12-20 23:34 UTC, Masaya-Kamei requested changes
- [ ] useProfileEdit にもクエリキーお願いします。
- [ ] hooks/api にあるindex.ts 整理お願いします。
- [ ] useFriends.ts にある、useIsFriend 、useFriendRelation.ts に移動して、friend-relation 使ったものにお願いします。
- [ ] block-relation のswagger の戻り値が、booleanになってたので、{ ~: boolean } に修正お願いします。
- [ ] friend のUserCard とprofile のMatchHistory のnickname にも、プロフィールページに飛ぶリンク仕込んでもいいと思いました。
- [ ] friend のRecognition だけ、全体がずれるのはなぜですか？ すぐ修正できそうになければ大丈夫です。

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/components/atoms/button/AcceptButton.tsx
> +  const { acceptFriendRequest } = useFriendRequestAccept(targetId);
isLoading 使って、ボタンくるくるさせてもよさそう。

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/features/friends/components/organisms/FriendsList.tsx
> +            <VStack justify="center" align="center">
いまのmain は横に並んでますが、縦にした理由はなんですか？
card の形が、ボタン１つと２つで、変わってるのが気になります。

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/features/friends/routes/Users.tsx
>          <TabPanels>
ここらで`<Suspense >`いれて、上のタブ部分は先に表示しておいてもいいと思いました。

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/BlockButton.tsx
>  export const BlockButton: FC<Props> = memo((props) => {
ここでは、components/atoms/button にあるボタン、使わないんですか？

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/features/friends/components/organisms/BlockedList.tsx
>            winRate={50}
winRate とtotalNumOfGames、api から取得するようにしてもいいと思いました！
UserCard の中でやるしかなさそう

2022-12-20 23:34 UTC, Masaya-Kamei commented on frontend/src/hooks/api/profile/useFriendRelation.ts
>    const {
このファイル、relation ディレクトリのほうが適切だと思います。
あと、relation ではなく、friend とかにした方がいいと思いました。

2022-12-21 01:16 UTC, sunix2019 commented on frontend/src/components/atoms/button/AcceptButton.tsx
> +  const { acceptFriendRequest } = useFriendRequestAccept(targetId);
isLoading, Spinner使うようにしました！

2022-12-21 02:33 UTC, sunix2019 commented on frontend/src/features/friends/routes/Users.tsx
>          <TabPanels>
Suspense挿入しました！

2022-12-21 02:35 UTC, sunix2019 commented on frontend/src/features/profile/components/BlockButton.tsx
>  export const BlockButton: FC<Props> = memo((props) => {
ここをBlockRelationButton変更。別にBlockボタンを作成して、それを使うようにしました！

2022-12-21 02:35 UTC, sunix2019 commented on frontend/src/components/atoms/button/AcceptButton.tsx
> +  const { acceptFriendRequest } = useFriendRequestAccept(targetId);
ついでにisDisableもつけました。

2022-12-21 02:52 UTC, sunix2019 commented on frontend/src/hooks/api/profile/useFriendRelation.ts
>    const {
friendに変更しました。

2022-12-21 04:03 UTC, yshima42 approved these changes
あまり指摘やいいこと言えなくて申し訳ないですが、とても整理されてて良いと思いました。

2022-12-21 06:42 UTC, sunix2019 commented on frontend/src/features/friends/components/organisms/BlockedList.tsx
>            winRate={50}
取得するように修正しました！

2022-12-21 06:42 UTC, sunix2019 commented on frontend/src/components/atoms/button/GameButton.tsx
> +  const onClickGame = () => {
ありがとうございます！

2022-12-21 07:58 UTC, Masaya-Kamei requested changes

2022-12-21 07:58 UTC, Masaya-Kamei commented on frontend/src/hooks/api/friend/useFriendRelation.ts
> +  const { users: friends } = useFriends();
useFriendRelation 使ってください！

2022-12-21 07:58 UTC, Masaya-Kamei commented on frontend/src/hooks/api/block/useUserBlockCancel.ts
>  export const useUserBlockCancel = (
useUserUnblock の方が適切だと思いました

2022-12-21 08:07 UTC, sunix2019 commented on frontend/src/hooks/api/friend/useFriendRelation.ts
> +  const { users: friends } = useFriends();
使うように修正しました！

2022-12-21 08:32 UTC, sunix2019 commented on frontend/src/hooks/api/block/useUserBlockCancel.ts
>  export const useUserBlockCancel = (
Unblock修正しました！

2022-12-21 08:43 UTC, Masaya-Kamei approved these changes
問題ないと思います。お疲れ様でした！！！

2022-12-21 08:43 UTC, merged