プロフィール編集とOTPのQRコードをモーダル化。
yshima42/ft_transcendence pull request #241
Opened 2022-12-22 02:28 UTC by sunix2019

2022-12-22 04:04 UTC, Masaya-Kamei reviewed
- [ ] Save したらモーダル閉じてもいいと思いました。
- [ ] Save したときのクエリキーの見直しをお願いします。アバターが更新されてない箇所があったので。
- [ ] routes にあるProfileEdit 消してもいいと思いました。

2022-12-22 05:09 UTC, hyoshie commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +            <OtpAuthButton />
[IMO]
コンポーネント名が並列になってるとよりよいと思いました。
ProfileEditModalの方がgitの件数多かったです。
https://github.com/search?q=Profileeditmodal&type=code

2022-12-22 05:12 UTC, hyoshie commented on frontend/src/features/profile/components/UserInfoCard.tsx
>          {isLoginUser ? (
[IMO]コンポーネントが肥大化してきてるので、コンポーネントを分割したいです。

2022-12-22 05:14 UTC, hyoshie requested changes
Save したときのクエリキーの見直しをお願いします。
モーダルはいい感じでした！

2022-12-22 07:37 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +            <OtpAuthButton />
該当部分を〇〇Buttonで並列になるように修正しました。
名前にModalがついていれば、名前から挙動がイメージできて良いと思ったので、とりあえず残しました。

2022-12-22 07:37 UTC, sunix2019 commented on frontend/src/features/profile/components/UserInfoCard.tsx
>          {isLoginUser ? (
コンポーネント分割してみました！

2022-12-23 01:36 UTC, Masaya-Kamei commented
最初のログインの場合、プロフィールエディットページに飛ぶようになってるので、モーダルダメかもです。
気づくの遅くて申し訳ないです。

2022-12-23 03:22 UTC, Masaya-Kamei requested changes

2022-12-23 03:22 UTC, Masaya-Kamei commented on frontend/src/components/atoms/button/AcceptButton.tsx
> +    <Button size={size} isDisabled={isLoading} onClick={onClickAccept}>
isSuccess はやらない？

2022-12-23 03:22 UTC, Masaya-Kamei commented on frontend/src/components/atoms/text/LinkedNickname.tsx
> +  const { id, nickname, maxWidth = 20 } = props;
デフォルトは1行全て表示の方がよさそう。

2022-12-23 03:22 UTC, Masaya-Kamei commented on frontend/src/features/profile/routes/ProfileEdit.tsx
>    useProfileEdit,
このファイル使ってます？　使ってなさそうなら削除お願いします！

2022-12-23 06:29 UTC, sunix2019 commented on frontend/src/components/atoms/text/LinkedNickname.tsx
> +  const { id, nickname, maxWidth = 20 } = props;
maxWidthのデフォルトnoneに修正しました。
http://www.htmq.com/style/max-width.shtml

2022-12-23 06:31 UTC, sunix2019 commented on frontend/src/components/atoms/button/AcceptButton.tsx
> +    <Button size={size} isDisabled={isLoading} onClick={onClickAccept}>
既存のAPIに一通りisSuccess追加しました。Friend一覧でのボタンにも適用させました。

2022-12-24 14:48 UTC, hyoshie commented on frontend/src/features/profile/components/UserInfoCard.tsx
> +            <OtpAuthButton />
了解です。
[nits]
個人的にはUserInfoCardの中に
プロフィール関連のコンポーネント
そのユーザーとの関係関連のコンポーネント
の2つがあって、その中にbuttonがある方がいいと思います。
コンポーネント名＝ファイル名を見て何をしているのか判断できるからです。

このままでも大丈夫です。

2022-12-24 14:49 UTC, hyoshie approved these changes
lgtm

2022-12-25 05:53 UTC, sunix2019 commented on frontend/src/features/profile/routes/ProfileEdit.tsx
>    useProfileEdit,
削除しました。

2022-12-25 07:31 UTC, Masaya-Kamei approved these changes
おつかれさまでした〜
問題ないと思います！

2022-12-25 07:31 UTC, merged