２要素認証有効化時にワンタイムパスワードを入力させるようにする。
yshima42/ft_transcendence pull request #250
Opened 2022-12-25 08:20 UTC by sunix2019

Closes #247

2022-12-26 01:18 UTC, Masaya-Kamei requested changes
- [ ] getOtpQrcodeUrl 関数の、ret === null のとき、よくないリクエストなので、例外投げた方がいいと思います。

2022-12-26 01:18 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
> +  ): Promise<{ isOtpAuthEnabled: boolean | null }> {
boolean ではダメですか？
フロントでは、null かどうか気にしたくないかもです。
サービスにある、 isOtpAuthEnabled 関数で、boolean を返すようにすればいい？

2022-12-26 01:18 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
> +  ): Promise<{ isOtpAuthEnabled: boolean | null }> {
create するときに、find して、なければ作るようにすれば、解決しそう。

2022-12-26 01:18 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
>    Redirect,
全体的に、service の関数の中で、処理書いてほしいです。
controller の中でやるのは、レスポンスに関わる部分のみ(cookie にセットしたり、リダイレクト先変えたり) に留めるのがいいかも。
あっちこっちいくのわかりにくいので、なるべく関数も少なくしてほしいです。

2022-12-26 01:18 UTC, Masaya-Kamei commented on backend/src/auth/strategy/jwt-otp.strategy.ts
> +    const { isOtpAuthEnabled } = await this.authService.isOtpAuthEnabled(
余裕あれば、１回のDBアクセスにできないですか？
ここ、毎回通るので、軽くしたい。
prisma のinclude 使えばできそう。
game.service のfindMatchHistory 関数とか参考になるかも。

2022-12-26 05:12 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
> +  @Patch('otp')
Corsエラーは＠Redirectによって生じていたみたいです！

2022-12-28 05:25 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
>    Redirect,
努力します。

2022-12-28 05:28 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
>    @Get('otp')
find関数を作成して、同じエンドポイントで出来るようにしました。

2022-12-28 05:29 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
> +  ): Promise<{ isOtpAuthEnabled: boolean | null }> {
必ずOtpAuthテーブルを持つようにしたので解消されたと思います。

2022-12-28 05:40 UTC, sunix2019 commented on backend/src/auth/strategy/jwt-otp.strategy.ts
> +    const { isOtpAuthEnabled } = await this.authService.isOtpAuthEnabled(
やってみました。

2022-12-29 02:45 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
>    Redirect,
ありがとうございます！
改善されたと思います！

2022-12-29 02:46 UTC, Masaya-Kamei commented on backend/src/auth/auth.service.ts
> +    const oneTimePasswordAuth = await this.prisma.oneTimePasswordAuth.update({
updateOtp 使ってもいいと思いました！

2022-12-29 02:53 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/organisms/OtpQrcodeModal.tsx
> +                <Button bg="teal.300" color="white" onClick={onClickSubmit}>
disable したほうがいいと思いました！

2022-12-29 02:58 UTC, Masaya-Kamei commented on backend/src/auth/strategy/jwt-otp.strategy.ts
> +    const { isOtpAuthEnabled } = await this.authService.isOtpAuthEnabled(
ありがとうございます！

2022-12-29 02:58 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
> +  ): Promise<{ isOtpAuthEnabled: boolean | null }> {
ありがとうございます！

2022-12-29 02:58 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
>    @Get('otp')
ありがとうございます！

2022-12-29 05:17 UTC, sunix2019 commented on backend/prisma/schema.prisma
> +  isOtpAuthEnabled Boolean  @default(false)
isEnabledにしました。

2022-12-29 05:17 UTC, sunix2019 commented on backend/src/auth/auth.service.ts
> +    const oneTimePasswordAuth = await this.prisma.oneTimePasswordAuth.update({
updateOtpを使うようにしました。

2022-12-29 05:39 UTC, sunix2019 commented on frontend/src/features/profile/components/organisms/OtpQrcodeModal.tsx
> +                <Button bg="teal.300" color="white" onClick={onClickSubmit}>
disable追加しました。

2022-12-29 05:48 UTC, sunix2019 commented on frontend/src/hooks/api/auth/useOtpQrcodeUrl.ts
> +export const useOtpAuthQrcodeUrl = (): {
useOtpAuthQrcodeCreateにしました。

2022-12-29 07:48 UTC, Masaya-Kamei approved these changes
問題ないと思います。お疲れ様でした！

2022-12-30 03:01 UTC, hyoshie commented on frontend/src/hooks/api/auth/useOtpAuthInactivate.ts
> +  const toast = useToast();
これいいですね！他の場所でも使えそう

2022-12-30 04:02 UTC, hyoshie approved these changes
LGTM

2022-12-30 04:07 UTC, merged