ワンタイムパスワード認証時のトークンを、PostAPIのボディで渡すようにしました。
yshima42/ft_transcendence pull request #251
Opened 2022-12-26 01:13 UTC by sunix2019

ログインするときに、ワンタイムパスワードをクエリでサーバーに渡していましたが、　セキュリティ上あまり良くないので、GETからPOSTメソッドに変更し、ボディとして渡すように変更しました。

Closes #248

2022-12-26 01:25 UTC, Masaya-Kamei approved these changes
なぜコルスエラー解決したのか知りたいです。

2022-12-26 01:25 UTC, Masaya-Kamei commented on backend/src/auth/auth.controller.ts
> +      const { accessToken } = await this.authService.generateJwt(
generateJwt 、service の中でやってもいいかも。

2022-12-26 01:30 UTC, Masaya-Kamei requested changes

2022-12-26 01:30 UTC, Masaya-Kamei commented on frontend/src/features/auth/routes/OtpAuth.tsx
> +    const { isCodeValid } = await validateOtpAuth({ oneTimePassword: token });
ログイン成功かどうか、レスポンスで判断せず、失敗の場合はバックエンド側で例外投げた方が良さそうだと思いました。

2022-12-28 04:45 UTC, sunix2019 commented on frontend/src/features/auth/routes/OtpAuth.tsx
> +    const { isCodeValid } = await validateOtpAuth({ oneTimePassword: token });
バックエンドで例外を投げるようにしました。

2022-12-28 14:11 UTC, sunix2019 commented on backend/src/auth/auth.controller.ts
> +      const { accessToken } = await this.authService.generateJwt(
service内で行うようにしました。

2022-12-29 10:05 UTC, yshima42 approved these changes
問題無いと思います。お疲れ様でした！

2022-12-30 02:25 UTC, closed without merging