Game/dev/countdown
yshima42/ft_transcendence pull request #252
Opened 2022-12-26 05:19 UTC by Masaya-Kamei

やったこと
- 準備OKや、相手待ち画面でカウントダウンされるようにした。０になったら無効試合となり部屋から追い出す。
- 最初と得点入ったあと、カウントダウン後に再開するようにした。

2022-12-26 06:37 UTC, yshima42 requested changes

2022-12-26 06:37 UTC, yshima42 commented on backend/src/game/game.object.ts
> +  countDownUntilGameRestart(): void {
原作pong gameにできるだけ合わせた実装にしたいです。https://www.ponggame.org/

2022-12-26 06:37 UTC, yshima42 commented on backend/src/game/game.object.ts
> +  countDownUntilPlayerReady(): void {
ラスト1秒くらいでAre you ready? Yesを押すと、ゲームが始まらない

2022-12-26 06:37 UTC, yshima42 commented on backend/src/game/game.object.ts
> +  countDownUntilPlayerReady(): void {
理由わからない。ごめんなさい。

2022-12-26 06:37 UTC, yshima42 commented on frontend/src/features/game/hooks/useGame.ts
> +    if (restartCountDownNum.current !== 0) {
元祖Pong game参考にすれば、秒数短めで表示はなしで良いのかなと思います。

2022-12-27 00:38 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +  countDownUntilGameRestart(): void {
カウントダウンの数字を表示しないようにしました。

2022-12-27 00:38 UTC, Masaya-Kamei commented on frontend/src/features/game/hooks/useGame.ts
> +    if (restartCountDownNum.current !== 0) {
1秒で表示無しにしました！

2022-12-27 00:44 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +          .emit('game_room_error', 'No player response.');
The game was canceled にしました。ありがとうございます！

2022-12-27 00:45 UTC, Masaya-Kamei commented on backend/src/game/game.object.ts
> +  countDownUntilPlayerReady(): void {
countDownUntilPlayerReady 関数の、if else  の順番変えて解決しました！

2022-12-27 01:23 UTC, yshima42 approved these changes
遅くなりました。とても良いと思います。

2022-12-27 01:23 UTC, merged