docker-comopose up -dでアプリが起動する
yshima42/ft_transcendence pull request #278
Opened 2022-12-29 05:56 UTC by hyoshie

### やったこと
- docker-comopose up -dでアプリが起動する

### やってないこと
- frontendを本番環境用にする（viteではなくnginxを使う）
- ファイルイメージの最小化
- peer dependencyの警告を消す
- docker-composeによる開発環境を用意する
- frontendがbackendの起動を待つ

### 確認方法
- .envファイルを用意する
　discordの開発＞6_環境＞本番環境用の.envを作るスクリプト
- makeで起動
- 42vmを使う場合は、makeの前に./setup-42vm.shを実行する
- 42vmが使える方はローカルと42vm両方で確認してください。

2022-12-29 09:35 UTC, Masaya-Kamei approved these changes
動作も問題なかったです。
お疲れ様でした！

2022-12-29 09:37 UTC, Masaya-Kamei commented on backend/package.json
> +    "nest:update": "nest update",
削除ありがとうございます！

2022-12-29 09:42 UTC, Masaya-Kamei commented on backend/setup-dev.sh
> -rm -rf "prisma/migrations"
修正ありがとうございます！

2022-12-29 11:39 UTC, Masaya-Kamei requested changes
VM で試してなかったので、試したらエラーでてたので、マージストップしました。
chat2 のpackage の影響かと。

<hr>

やってないことの、「frontendがbackendの起動を待つ」
cypress のテスト動かす際に使ったstart-server-and-test パッケージ、使えそうであれば。
https://github.com/yshima42/ft_transcendence/wiki/%E7%92%B0%E5%A2%83%E6%95%B4%E5%82%99#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8B%E3%81%BE%E3%81%A7%E5%BE%85%E6%A9%9F

<hr>

一応報告で、VMで、./setup-42vm.sh したら以下のエラーでたけど、指示通り`sudo dpkg --configure -a`したら、解決しました。
```
+ sudo apt install google-chrome-stable firefox
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

2022-12-29 11:42 UTC, Masaya-Kamei commented
やってないことの、「frontendがbackendの起動を待つ」
cypress のテスト動かす際に使ったstart-server-and-test パッケージ、使えそうであれば。
https://github.com/yshima42/ft_transcendence/wiki/%E7%92%B0%E5%A2%83%E6%95%B4%E5%82%99#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E8%B5%B7%E5%8B%95%E3%81%99%E3%82%8B%E3%81%BE%E3%81%A7%E5%BE%85%E6%A9%9F

2022-12-29 11:42 UTC, Masaya-Kamei commented
一応報告で、VMで、./setup-42vm.sh したら以下のエラーでたけど、指示通り`sudo dpkg --configure -a`したら、解決しました。
```
+ sudo apt install google-chrome-stable firefox
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
```

2022-12-29 15:27 UTC, hyoshie commented
> VM で試してなかったので、試したらエラーでてたので、マージストップしました。 chat2 のpackage の影響かと。

- prismaの型が生成されていない
- 必要なモジュールがdependencyにない
が原因でした。
確認よろしくお願いします。

2022-12-30 01:09 UTC, sunix2019 commented
42vmで42AuthでログインしようとしたらInternal server errorが僕の環境では起きたので、一応報告しておきます。

2022-12-30 01:49 UTC, sunix2019 approved these changes
mac, 42vmどちらも起動されていたと思います！
package.json本当ナイスファイでした！

2022-12-30 02:33 UTC, Masaya-Kamei approved these changes
ローカルmac、42vm 共に問題なく動いてそうでした。
お疲れ様でした〜

2022-12-30 02:33 UTC, merged