Chat3
yshima42/ft_transcendence pull request #301
Opened 2023-01-05 15:48 UTC by kohkubo

やったことはこんな感じ。

https://github.com/yshima42/ft_transcendence/issues/288

2023-01-06 06:02 UTC, hyoshie commented
```typescript
[Nest] 25248  - 01/06/2023, 2:55:28 PM   ERROR [WsExceptionsHandler] 
Invalid `this.prisma.chatMessage.create()` invocation in
/home/user42/42tokyo/ft_transcendence/backend/src/chat-message/chat-message.service.ts:16:55

  13   createChatMessageDto: CreateChatMessageDto,
  14   senderId: string
  15 ): Promise<ResponseChatMessage> {
→ 16   const chatMessage = await this.prisma.chatMessage.create({
         data: {
           content: 'dddd',
           chatRoomId: '353a3f01-f244-4b71-8539-3d37093d3f21',
       +   senderId: String,
       ?   id?: String,
       ?   createdAt?: DateTime
         },
         select: {
           id: true,
           content: true,
           createdAt: true,
           sender: {
             select: {
               id: true,
               name: true,
               avatarImageUrl: true
             }
           }
         }
       })

Argument senderId for data.senderId is missing.
```
dummy1でログインした後、メッセージを送れませんでした。
修正お願いします。

2023-01-06 06:12 UTC, hyoshie commented
今回のプルリク範囲外かもしれませんが、存在しないchatroomのuuidをurlに含めるとUnexpected Errorページに遷移しました。
http://localhost:5173/app/chat/rooms/aaa

発見した経緯
ブラウザ1でchatroomに入る
ブラウザ2でchatroomに入り、そのルームをdeleteする
ブラウザ1の画面をリロードする

2023-01-06 06:48 UTC, hyoshie commented
以下のフローで、DMルームが表示されないバグがありました。
dummy1がdummy2のブロックを解除する
dummy1からdummy2にDMを送る
dummy1のDMページにdummy2とのDMルームが表示されない
dummy2のDMページにはdummy1とのDMルームが表示される

2023-01-06 06:53 UTC, Masaya-Kamei commented
create chat room のとき、Private　も作れた方がいいと思いました！

2023-01-06 06:54 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
> +import * as React from 'react';
create chat room のとき、Private room も作れた方がいいと思いました！

2023-01-06 07:03 UTC, hyoshie commented on backend/src/chat/chat.gateway.ts
> +      client.data.userId as string
client.data.userIdがundefinedになっていました。
このgatewayでデータを紐付けていないからだと思います。
mainブランチのbackend/src/socket/socket.gateway.tsを参考にしてください。

2023-01-06 07:12 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoomConfirmationPage.tsx
> +              {...register('password', {
正しいpassword 入力しても入れないっぽいです！

2023-01-06 07:14 UTC, hyoshie commented on frontend/src/features/dm/routes/DmRoom.tsx
> +      queryClient.setQueryData(
いい書き方ですね！

2023-01-06 07:16 UTC, hyoshie commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +          return null;
[nits]ここは省略してよかった気がします。

2023-01-06 07:21 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/DmRoom.tsx
> +  const { dmRoomId, memberId } = location.state as State;
直打ち対応するため、location.state 使わないよう修正お願いします！

2023-01-06 07:24 UTC, hyoshie commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
> +import * as React from 'react';
> create chat room のとき、Private room も作れた方がいいと思いました！

おそらくPrivate room作成後にjoinできない仕様になってると思います。
関連して、
非公開チャットにアクセスできないケースがありました。
Chat Membersに入っていないユーザーで非公開チャットのURLにアクセスすると、Unexpected Errorページに遷移しました。
期待した動作ですか？

個人的には、非公開チャットに新しいユーザーが入室するフローがあった方がいいと思いますが、サブジェクトには書いていないので非機能要件です。
対応するかはおまかせします。

2023-01-06 07:25 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoomPage.tsx
> +import * as React from 'react';
参加していないchat-room に直打ち(/app/chat/rooms/:id) でアクセスすると、エラー起きました！

2023-01-06 07:27 UTC, hyoshie requested changes
大量の機能追加、お疲れ様でした。
今回のプルリク範囲外のバグもコメントしました。
必要なら別イシューにしてください。

よろしくお願いします。

2023-01-06 07:31 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoomConfirmationPage.tsx
>  import * as React from 'react';
既に参加してるチャットルームのconfirmation ページに直打ちでいくと(app/chat/rooms/:id/confirmation )、confirmation ページ表示されて、joinボタン押すと、アラート出て入れなかったです。
バグではないので、修正必須ではないですが、ページアクセスした瞬間リダイレクトするか、joinボタンで入れるようにするかしたほうが親切だと思いました！

2023-01-06 07:38 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
> +import * as React from 'react';
> 非公開チャットにアクセスできないケースがありました。
> Chat Membersに入っていないユーザーで非公開チャットのURLにアクセスすると、Unexpected Errorページに遷移しました。
> 期待している動作ですか？

これは、非公開チャット関係なく、参加していないルームのurl ページいくと、エラーなりました！

2023-01-06 07:42 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
> +import * as React from 'react';
> 個人的には、非公開チャットに新しいユーザーが入室するフローがあった方がいいと思いますが

/app/chat/rooms/:id/confirmation でjoin できると思います！

2023-01-06 07:44 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/atoms/Spinner.tsx
> +import * as React from 'react';
src/components/atoms/spinner に、 CenterSpinner コンポーネントがあるので、使ってもいいと思いました！

2023-01-06 07:49 UTC, hyoshie commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
> +import * as React from 'react';
> > 個人的には、非公開チャットに新しいユーザーが入室するフローがあった方がいいと思いますが
> 
> /app/chat/rooms/:id/confirmation でjoin できると思います！

見落としてました。失礼しました。

2023-01-06 07:55 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoomPage.tsx
> +import * as React from 'react';
banされたユーザーが直打ちでアクセスするとチャットルーム入れたので、入れない方がいいと思いました！

2023-01-06 08:02 UTC, kohkubo commented
> ```ts
> [Nest] 25248  - 01/06/2023, 2:55:28 PM   ERROR [WsExceptionsHandler] 
> Invalid `this.prisma.chatMessage.create()` invocation in
> /home/user42/42tokyo/ft_transcendence/backend/src/chat-message/chat-message.service.ts:16:55
> 
>   13   createChatMessageDto: CreateChatMessageDto,
>   14   senderId: string
>   15 ): Promise<ResponseChatMessage> {
> → 16   const chatMessage = await this.prisma.chatMessage.create({
>          data: {
>            content: 'dddd',
>            chatRoomId: '353a3f01-f244-4b71-8539-3d37093d3f21',
>        +   senderId: String,
>        ?   id?: String,
>        ?   createdAt?: DateTime
>          },
>          select: {
>            id: true,
>            content: true,
>            createdAt: true,
>            sender: {
>              select: {
>                id: true,
>                name: true,
>                avatarImageUrl: true
>              }
>            }
>          }
>        })
> 
> Argument senderId for data.senderId is missing.
> ```
> 
> dummy1でログインした後、チャットでメッセージを送れませんでした。 修正お願いします。

環境変数周りかな？こっちでは動く

```
VITE_APP_TITLE=My Super Awsome APP
VITE_API_URL="http://localhost:3000"
VITE_WS_BASE_URL="http://localhost:3000"
VITE_WS_CHAT_URL="http://localhost:3000/chat"
VITE_WS_DM_URL="http://localhost:3000/dm"

DATABASE_URL="postgresql://udemy:udemy@localhost:5434/udemy?schema=public"
```

2023-01-06 08:03 UTC, kohkubo commented
@hyoshie コメント返す形にできないから、レビューに関しては、レビューの項目からコメント投げてほしいです！

2023-01-06 08:07 UTC, kohkubo commented
> 以下のフローで、DMルームが表示されないバグがありました。
> dummy1がdummy2のブロックを解除する
> dummy1からdummy2にDMを送る
> dummy1のDMページにdummy2とのDMルームが表示されない
> dummy2のDMページにはdummy1とのDMルームが表示される

一部は仕様かな？
このappにおけるブロックは自分から見えなくなるだけで、相手から見える状態になります。
@hyoshie

2023-01-06 09:01 UTC, kohkubo commented on frontend/src/features/dm/routes/DmRoom.tsx
> +  const { dmRoomId, memberId } = location.state as State;
- [ ] 戻る、進むで動くかチェック

2023-01-06 09:04 UTC, kohkubo commented on frontend/src/features/dm/routes/DmRoom.tsx
> +  const { dmRoomId, memberId } = location.state as State;
- [ ] 直打ちに対応して、ちゃんと最初に見る

2023-01-06 09:05 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomPage.tsx
> +import * as React from 'react';
- [ ] チャットルーム一覧に遷移するようにする？？

2023-01-06 09:21 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomPage.tsx
> +import * as React from 'react';
後回し、かめいさんに方針決めてもらう。

2023-01-06 09:33 UTC, hyoshie reviewed
https://github.com/yshima42/ft_transcendence/pull/301#issuecomment-1373320162
envは同じでした。cloneし直しましたが、同じエラーが起きました。
My Chatに最初からあるチャットルームで試しました。

おそらくhttps://github.com/yshima42/ft_transcendence/pull/301#discussion_r1063188568
の問題だと思います。

2023-01-06 10:03 UTC, hyoshie commented
> @hyoshie コメント返す形にできないから、レビューに関しては、レビューの項目からコメント投げてほしいです！

今後そうします。
https://github.com/yshima42/ft_transcendence/pull/301#discussion_r1063203803
のように、コードの特定の部分にコメントする形で合ってますか？

今回はまとめてここに書きますね。
○https://github.com/yshima42/ft_transcendence/pull/301#issuecomment-1373320162
.envは同じでした。cloneし直して記載の.envを使っても同じエラーが出ました。
https://github.com/yshima42/ft_transcendence/pull/301#discussion_r1063188568
の問題だと思います。

○https://github.com/yshima42/ft_transcendence/pull/301#issuecomment-1373325606
ブロックを解除した（＝現在ブロック関係がない）あとDMのやりとりをしたのに、DMRoomが表示されないですね。
もともとブロック関係がないdummy2とdummy3でDMすると、両方のユーザーのDMRoomに表示されました。
原因までは調べてないのですが、確認お願いします。

@kohkubo

2023-01-08 03:04 UTC, kohkubo commented on frontend/src/features/chat/components/atoms/Spinner.tsx
> +import * as React from 'react';
消し忘れでした。消去しました。

2023-01-08 03:18 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomPage.tsx
> +import * as React from 'react';
漏れてますね。対応しました。

2023-01-08 03:22 UTC, kohkubo commented on backend/src/chat/chat.gateway.ts
> +      client.data.userId as string
handleConnectionの処理を消したときに、更新し忘れていました。対応しました。

2023-01-08 03:24 UTC, kohkubo commented on backend/src/chat/chat.gateway.ts
> +    const cookie = client.handshake.headers.cookie;
途中でクッキーが消失する場合とか考えないいけないケースないかな？
とりあえず現状ままの実装にしておきました。

2023-01-08 03:26 UTC, Masaya-Kamei commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
chat-room.controller のエンドポイントの返り値、`ResponseChatRoom` か`<Omit<ChatRoom, 'password'>>` に統一してほしいです！
ここは、Promise<ResponseChatRoom> ではダメですか？

2023-01-08 03:27 UTC, Masaya-Kamei commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<void> {
void ではなく、更新後の`ResponseChatRoom` か`Omit<ChatRoom, 'password'>`を返した方がいいと思いました！

2023-01-08 03:35 UTC, Masaya-Kamei commented on backend/src/chat-room/chat-room.service.ts
>    async findAllWithOutMe(userId: string): Promise<ResponseChatRoom[]> {
プライベートもはじくので、findAllWithOutMeは、findJoinableRooms かfindAllJoinable 等のほうが適切だと思いました！
合わせて、findAllByMe も、findJoinedRooms かfindAllJoined の方がいいと思いました！

2023-01-08 03:44 UTC, Masaya-Kamei commented on frontend/src/components/atoms/button/DmButton.tsx
> +        alert(error.response.data?.message ?? 'error');
message がエラー出てるので、`isAxiosError<{ message: string }>(error)` 使うといいと思います！

2023-01-08 03:48 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/atoms/AlertModal.tsx
> +import * as React from 'react';
src/components/molecules にも、全く同じ？AlertModal.tsx あるので、どちらか削除でお願いします！
というか、使ってないっぽい？ であれば、消してもいいかもです！

2023-01-08 03:58 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +            {hasLimitTime ? (
ここで、hasLimitTime の分岐せずに、ChatRoomMemberButtonWithLimitTime と、ChatRoomMemberButtonを、合体させて、
```
            {hasLimitTime ? (
    <C.Popover>
      ~
    </C.Popover>  ) : (
              <C.Button onClick={handleClick}>{text}</C.Button>
            )}
```
の方がスッキリすると思いました！

2023-01-08 04:00 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +        hasLimitTime: false,
以下を作る関数作れば、スッキリしそうだと思いました！
```
      {
        memberStatus: ChatRoomMemberStatus.KICKED,
        label: 'Kick',
        hasLimitTime: false,
      }
```

2023-01-08 04:09 UTC, Masaya-Kamei commented on frontend/src/components/molecules/Message.tsx
> +      <C.Text fontSize="sm" fontWeight="bold">
LinkedAvatar 使うといいと思います！

2023-01-08 04:11 UTC, Masaya-Kamei commented on frontend/src/hooks/api/generics/usePostApi2.ts
> +import {
usePostApi と同じ?なので、usePostApi で良さそうだと思いました！

2023-01-08 05:00 UTC, Masaya-Kamei commented on frontend/src/hooks/api/generics/usePostApi2.ts
> +import {
usePostApi と同じ?なので、usePostApi で良さそうだと思いました！

2023-01-08 05:02 UTC, Masaya-Kamei requested changes
実装お疲れ様でした！
前回指摘できなかったバグが多くて、申し訳ないです。
確認よろしくお願いします！

2023-01-08 05:33 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomConfirmationPage.tsx
>  import * as React from 'react';
confirmationにアクセスするときにユーザーの状態をチェックするようにしました。

BANのとき-> ルーム一覧に遷移
参加しているとき-> ルーム内に遷移

2023-01-08 05:34 UTC, kohkubo commented
- [ ] DMのgatewayでDTOする

2023-01-08 05:42 UTC, kohkubo commented on frontend/src/components/molecules/Message.tsx
> +      <C.Text fontSize="sm" fontWeight="bold">
プロフィールページがmeでなくて、自分のIDでもアクセスできるように変更された後に変えようと思います。

2023-01-08 05:44 UTC, kohkubo commented on frontend/src/hooks/api/generics/usePostApi2.ts
> +import {
けしました！

2023-01-08 05:51 UTC, kohkubo commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +        hasLimitTime: false,
補完で生成するから記述が冗長なのはあんまり気にならないんだけど、関数作ってみました。確かにスッキリしたかも。

2023-01-08 05:56 UTC, kohkubo commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +            {hasLimitTime ? (
確かにそうですね。リファクタリングとして別プルリクに回します。

2023-01-08 06:03 UTC, kohkubo commented on frontend/src/components/atoms/button/DmButton.tsx
> +        alert(error.response.data?.message ?? 'error');
isAxiosError知りませんでした。いいですね。変えました。

2023-01-08 06:04 UTC, kohkubo commented on frontend/src/features/chat/components/atoms/AlertModal.tsx
> +import * as React from 'react';
消しました！

2023-01-08 06:07 UTC, kohkubo commented on backend/src/chat-room/chat-room.service.ts
>    async findAllWithOutMe(userId: string): Promise<ResponseChatRoom[]> {
確かに！

2023-01-08 06:22 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/organisms/ChatRoomMemberList.tsx
> +      const fetchDate = async () => {
綴り、fetchData

2023-01-08 06:25 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoomSettingsPage.tsx
> +  useGetApi<ResponseChatRoomMember>(`/chat/rooms/${chatRoomId}/members/me`);
この行、消して良さそう

2023-01-08 07:47 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomSettingsPage.tsx
> +import * as React from 'react';
作成時に設定するようにしました！

2023-01-08 07:47 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomConfirmationPage.tsx
> +              {...register('password', {
8文字以下でエラー出すようにしました！

2023-01-08 07:49 UTC, kohkubo commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +          return null;
？？
MODERATORはアドミンに対して処理ができないようにボタンを出し分ける必要があるから必要では？？

2023-01-08 07:50 UTC, kohkubo commented on frontend/src/features/dm/routes/DmRoom.tsx
> +  const { dmRoomId, memberId } = location.state as State;
これ、存在しないURLに対する動作の方針が決まってから見直します！

2023-01-08 07:57 UTC, kohkubo commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
ResponseChatRoomは配列のときのみ使うので、エンドポイントして役割が異なり、別でも良いと思うのですが、どういったモチベーションで統一したいのでしょうか？

2023-01-08 07:59 UTC, kohkubo commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<void> {
この関数自体使わなくなったので消去しました。

2023-01-08 08:38 UTC, kohkubo commented on frontend/src/features/chat/components/organisms/ChatRoomMemberList.tsx
> +      const fetchDate = async () => {
直しました！

2023-01-08 08:38 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoomSettingsPage.tsx
> +  useGetApi<ResponseChatRoomMember>(`/chat/rooms/${chatRoomId}/members/me`);
確かに！

2023-01-08 08:51 UTC, kohkubo commented on frontend/src/features/chat/components/organisms/ChatRoomMemberList.tsx
> +      const fetchDate = async () => {
直しました！

2023-01-09 02:52 UTC, Masaya-Kamei commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
rooms とrooms/:id で、返り値の型が異なるのは、設計として綺麗ではないと思いました。
逆に変えたいモチベーション知りたいです！
特別な理由があればいいと思いますが、今回は、`ResponseChatRoom` か`Omit<ChatRoom, 'password'>`のどちらかに統一できそうだと思いました！

2023-01-09 02:55 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/atoms/ChangeChatRoomMemberStatusButtons.tsx
> +        hasLimitTime: false,
読むときに、行数少ない方が俯瞰しやすいなぁと思って、コメントしました！

2023-01-09 02:58 UTC, Masaya-Kamei commented on backend/prisma/seed.ts
> +  // await prisma.friendRequest.createMany({
このseed もうちょっと使いやすくしたいですね。
とりあえずは、毎回フレンドになる手間があるので、残しておいてもらえませんか？

2023-01-09 02:58 UTC, kohkubo commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
設計としての美しさと実用性は別で、それはパフォーマンスを追求するとコードの抽象度が下がるのと同じ理屈だと思う。

今回は不要な情報の連携を避けようとするとエンドポイントごとに返り値の型は変わるようになると思う。

綺麗さのために不要な情報の連携をするよりは、必要な情報だけ連携する方がいいという考えです。

2023-01-09 03:01 UTC, kohkubo commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
ResponseChatRoomに関してはルームの最終更新日時とメッセージを持つことで、LINEのルーム一覧みたいに一覧から最新のメッセージの一部が見えるような拡張をできるようにしているから残したいって感じ

2023-01-09 03:08 UTC, hyoshie approved these changes
指摘した箇所が修正されていることを確認しました！

2023-01-09 03:20 UTC, Masaya-Kamei approved these changes
バグ直っていること、確認できました！
seed の件だけ確認よろしくお願いします。
まだresolved していない箇所があるので、マージはやらないです！

2023-01-09 03:47 UTC, Masaya-Kamei commented on backend/src/chat-room/chat-room.controller.ts
> +  ): Promise<Omit<ChatRoom, 'password'>> {
rooms/:id をResponseChatRoom にはできないんですか？
フロントでは、このエンドポイントとメッセージ一覧の取得の2回叩いてるのが、1回にならない？
見当違いであればすみません！

2023-01-09 03:58 UTC, kohkubo commented on backend/prisma/seed.ts
> +  // await prisma.friendRequest.createMany({
入れました！

2023-01-09 04:05 UTC, merged