Fix api generics
yshima42/ft_transcendence pull request #306
Opened 2023-01-06 02:48 UTC by Masaya-Kamei

2023-01-06 06:05 UTC, yshima42 approved these changes
問題ないと思います。

2023-01-06 08:59 UTC, kohkubo requested changes

2023-01-06 08:59 UTC, kohkubo commented on frontend/src/hooks/api/generics/usePostApi.ts
> -          void queryClient.invalidateQueries({ queryKey });
- [ ] invalidateQueriesは共通して使っている部分が多いので、ラッパー関数として残しておいてもいいと思います。
- [ ] トーストの処理も共通している部分が多いようなので、新たにラッパー関数を作ってもいいと思います。
- [ ] onErrorを使って書いたほうが可読性が上がります。

2023-01-06 10:11 UTC, Masaya-Kamei commented
- 更新系のgenerics は、無効にするqueryKeys を受け取って、onSuccess 内でクエリ無効化する元々の実装に戻しました！
- 更新系のgenerics に、onError でトースト表示する、新しいラッパー関数作りました！

2023-01-08 05:23 UTC, kohkubo requested changes

2023-01-08 05:23 UTC, kohkubo commented on frontend/src/hooks/api/generics/useDeleteApi.ts
>            void queryClient.invalidateQueries({ queryKey });
最初に指摘できなくてすみません。
deleteのエンドポイントに関してはinvalidateQueriesではなく、resetQueriesを使ったほうが、バグを防げるケースが多いようにおもうのですが、どうでしょう？

2023-01-08 05:54 UTC, Masaya-Kamei commented on frontend/src/hooks/api/generics/useGetApi.ts
> +export function useCustomGetApi<ResBody>(
確かに説明になってないですね。。 
useGetApiOmitUndefined にしました！

2023-01-08 05:58 UTC, Masaya-Kamei commented on frontend/src/hooks/api/generics/useDeleteApi.ts
>            void queryClient.invalidateQueries({ queryKey });
たしかに、存在しないリソースの場合、古い情報表示する動機ないですね。
resetQueries にします！

2023-01-08 06:27 UTC, kohkubo approved these changes

2023-01-08 06:27 UTC, merged