Error handling/not found
yshima42/ft_transcendence pull request #312
Opened 2023-01-09 02:24 UTC by Masaya-Kamei

2023-01-09 03:19 UTC, hyoshie approved these changes
エラー表示まで少し時間があるのが気になりました。余裕があれば対応検討しましょう。

2023-01-09 09:38 UTC, kohkubo approved these changes

2023-01-09 09:38 UTC, kohkubo commented on frontend/src/providers/ErrorProvider.tsx
> +        return <Navigate to="/app/users" />;
return <Navigate to="/" />;
で良いように思いました。
ユーザーページにはマッチヒストリーとかいろいろなところから行けるので

2023-01-09 09:38 UTC, kohkubo commented on frontend/src/providers/ErrorProvider.tsx
> +        isProfilePage &&
バレットプルーフみたいにルートの処理自体を各featureに分けてエラーバンダリーを各featureに使うような設計にできませんか？
動的なURLを使っているfeatureは分ける意味があると思いました。

12日までなので、時間との相談ですね。ただ、ここにCHATの場合の分岐を書き足すのはなかなか骨が折れそう。。。

2023-01-09 09:38 UTC, kohkubo commented on frontend/src/routes/PublicRoutes.tsx
> +        {/* TODO:AppProviderファイルに書きたい。認証後にオンライン状態にしたいのでここに書いている。ルーティング周りのリファクタ時に修正する。 */}
よしえさんが書いたらしく、もうやらないと思うので消して良いそうです。

2023-01-09 09:40 UTC, kohkubo requested changes

2023-01-09 09:40 UTC, kohkubo commented on frontend/src/routes/PublicRoutes.tsx
> +        {/* TODO:AppProviderファイルに書きたい。認証後にオンライン状態にしたいのでここに書いている。ルーティング周りのリファクタ時に修正する。 */}
よしえさんが書いたらしく、もうやらないと思うので消して良いそうです。

2023-01-09 23:48 UTC, Masaya-Kamei commented on frontend/src/providers/ErrorProvider.tsx
> +        return <Navigate to="/app/users" />;
<Navigate to="/app" /> にしました！

2023-01-09 23:49 UTC, Masaya-Kamei commented on frontend/src/providers/ErrorProvider.tsx
> +        isProfilePage &&
指摘ありがとうございました！
features ごとに、routes 用意しました！

2023-01-09 23:50 UTC, Masaya-Kamei commented on frontend/src/routes/PublicRoutes.tsx
> +        {/* TODO:AppProviderファイルに書きたい。認証後にオンライン状態にしたいのでここに書いている。ルーティング周りのリファクタ時に修正する。 */}
消しました！

2023-01-10 01:08 UTC, kohkubo approved these changes
Good

2023-01-10 01:08 UTC, merged