Chat4
yshima42/ft_transcendence pull request #344
Opened 2023-01-10 10:03 UTC by kohkubo

2023-01-10 10:18 UTC, kohkubo commented on backend/src/__tests__/users.service.spec.ts
> -import { ConfigService } from '@nestjs/config';
テストのスコープがDBに依存しており、新たにテストを書く際に干渉するため消去しました。

2023-01-10 10:18 UTC, kohkubo commented on backend/src/__tests__/game.service.spec.ts
> -import { BadRequestException } from '@nestjs/common';
テストのスコープがDBに依存しており、新たにテストを書く際に干渉するため消去しました。

2023-01-10 10:18 UTC, kohkubo commented on backend/src/__tests__/blocks.service.spec.ts
> -import { BadRequestException, NotFoundException } from '@nestjs/common';
テストのスコープがDBに依存しており、新たにテストを書く際に干渉するため消去しました。

2023-01-10 10:18 UTC, kohkubo commented on backend/package.json
> -    "test:runInBand": "prisma migrate reset -f --skip-seed && jest --runInBand && prisma migrate reset -f",
使ってないので消去

2023-01-10 10:18 UTC, kohkubo commented on backend/prisma/migrations/20230110060252_init/migration.sql
> -CREATE TYPE "ChatRoomMemberStatus" AS ENUM ('ADMIN', 'MODERATOR', 'NORMAL', 'KICKED', 'BANNED', 'MUTED');
名前変更

2023-01-10 10:18 UTC, kohkubo commented on backend/prisma/schema.prisma
> -  source   User   @relation("source", fields: [sourceId], references: [id])
テスト時にDBをクリーンするときにカスケードがついてないとゴミが残る

2023-01-10 10:18 UTC, kohkubo commented on backend/src/chat-message/chat-message.service.ts
> -            name: true,
表示名をニックネームに変更

2023-01-10 10:18 UTC, kohkubo commented on backend/src/chat-room-member/chat-room-member.service.ts
> -      // ADMIN -> ADMINの場合は変更に加えて、自分のステータスをMODERATORに変更する
OWNERが権限を移譲できないように変更

2023-01-10 13:57 UTC, sunix2019 reviewed
Issue対応おつかれさまです！
コード理解しきれていないですが、挙動で気になった部分をコメントしておきます。

- chatでownerがsettingsにアクセスした時、以下が生じました。
  - [ ]  kick, ban~等のボタンが表示されませんでした。
  - [ ] Exitボタンが表示され、クリックするとconsoleにaxiosエラーが表示されました。
  - [x] 加えて、public, private, protectのボタンが表示されますが、一回クリックすると、そのボタンの状態に変化して、もう一度クリックするとchat room内に移動しました。意図した挙動ですか？
 - chatで一般ユーザーでsettingsにアクセスした時も
   - [x] public~のボタンが表示されますが、クリックするとconsoleにaxiosエラーが表示されていました。

確認よろしくおねがいします。

2023-01-10 13:57 UTC, sunix2019 commented on backend/src/__tests__/chat-mesage.service.spec.ts
> +// import * as NestJs from '@nestjs/common';
ファイル名タイポありました。

2023-01-10 23:21 UTC, Masaya-Kamei commented on frontend/package.json
> -    "lint:style:fix": "stylelint --fix 'src/**/*.{css,less,sass,scss}'",
css 書いてないけど、今後書くこともあるかもだし、残しておいてもいいのでは？

2023-01-10 23:23 UTC, Masaya-Kamei commented on frontend/src/features/auth/components/DummyAuthButton.tsx
> +      OWNER Test {dummyId}
ログインする時のボタンなので、Admin のままでいいと思います！

2023-01-10 23:25 UTC, Masaya-Kamei commented on frontend/src/components/molecules/Message.tsx
>        </C.Text>
LinkedNickname 使ってもいいと思いました！

2023-01-10 23:30 UTC, Masaya-Kamei commented on frontend/src/features/chat/components/organisms/ChatRoomMemberList.tsx
>          <C.Text ml={10}>{member.user.nickname}</C.Text>
LinkedNickname 使ってもいいと思いました！

2023-01-10 23:40 UTC, Masaya-Kamei commented on backend/src/__tests__/blocks.service.spec.ts
> -import { BadRequestException, NotFoundException } from '@nestjs/common';
一時的にということですか？
そうでないなら、修正を依頼してほしいです。せっかく書いたので。

2023-01-10 23:41 UTC, Masaya-Kamei commented on backend/src/__tests__/game.service.spec.ts
> -import { BadRequestException } from '@nestjs/common';
一時的にということですか？
そうでないなら、修正を依頼してほしいです。せっかく書いたので。

2023-01-10 23:47 UTC, Masaya-Kamei commented on backend/prisma/seed.ts
以前指摘できず、申し訳ないです。
seed で用意されたチャットルーム、メンバーがいないルームがあって、Join すると、NORMAL ユーザー１人だけになってて、初期データとして不適切だと思いました！
あとできれば、チャットルーム名、dmRoom ではなく、chatRoom にしたほうがわかりやすいと思いました！

2023-01-10 23:56 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/DmRoom.tsx
>                    id={message.id}
issue としてあがってなかったので一応。
dmRoom の直打ちアクセスに、対応お願いします！

2023-01-10 23:59 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoom/ChatRoomPage.tsx
>        socket.emit('leave_room_member', chatRoomId);
issue としてあがってなかったので一応。
/chat/rooms/:id のid が無効だった場合と、参加していないチャットルームに直打ちアクセス、に対応お願いします！

2023-01-11 00:02 UTC, Masaya-Kamei commented on backend/src/__tests__/users.service.spec.ts
> -import { ConfigService } from '@nestjs/config';
一時的にということですか？
そうでないなら、修正を依頼してほしいです。せっかく書いたので。

2023-01-11 00:05 UTC, Masaya-Kamei requested changes
ご確認よろしくお願いします！

2023-01-11 00:29 UTC, kohkubo commented
> Issue対応おつかれさまです！
> 
> コード理解しきれていないですが、挙動で気になった部分をコメントしておきます。
> 
> 
> 
> - chatでownerがsettingsにアクセスした時、以下が生じました。
> 
>   - [ ]  kick, ban~等のボタンが表示されませんでした。
> 
>   - [ ] Exitボタンが表示され、クリックするとconsoleにaxiosエラーが表示されました。
> 
>   - [ ] 加えて、public, private, protectのボタンが表示されますが、一回クリックすると、そのボタンの状態に変化して、もう一度クリックするとchat room内に移動しました。意図した挙動ですか？
> 
>  - chatで一般ユーザーでsettingsにアクセスした時も
> 
>    - [ ] public~のボタンが表示されますが、クリックするとconsoleにaxiosエラーが表示されていました。
> 
> 
> 
> 確認よろしくおねがいします。

ブラウザのキャッシュをクリアすると正しく動くかも！

2023-01-11 00:35 UTC, kohkubo commented on frontend/package.json
> -    "lint:style:fix": "stylelint --fix 'src/**/*.{css,less,sass,scss}'",
意図しないバグが出ているのかどうかがわからないので、必要になった時に、追記すれば良いと思います。

2023-01-11 02:09 UTC, sunix2019 commented
> ブラウザのキャッシュをクリアすると正しく動くかも！

キャッシュ消しても動かないかもです＞＜

2023-01-11 03:07 UTC, kohkubo commented on frontend/src/features/chat/components/organisms/ChatRoomMemberList.tsx
>          <C.Text ml={10}>{member.user.nickname}</C.Text>
書換えました

2023-01-11 03:08 UTC, kohkubo commented on backend/prisma/seed.ts
書換えました！

2023-01-11 05:04 UTC, Masaya-Kamei commented on frontend/package.json
> -    "lint:style:fix": "stylelint --fix 'src/**/*.{css,less,sass,scss}'",
「意図しないバグが出ているのかどうかがわからない」とはどういうことですか？
このlint は、関係あるんですか？

2023-01-11 05:11 UTC, Masaya-Kamei commented
> ブラウザのキャッシュをクリアすると正しく動くかも！
自分もせきぐちさんと同じバグ確認してます。キャッシュ消しても動かないかもです！

2023-01-11 08:10 UTC, sunix2019 commented
追加で気になったのですが、レビュー項目に以下の文言がありました。現状、自分がブロックしていても、相手側はメッセージを送れてしまうので、ブロックを解除した場合、メッセージが受け取れてしまうと思いました。

「ユーザーは、他のユーザーをブロックすることができます。**この場合、ブロックしたアカウントからのプライベートメッセージは受け取れませんし**、公開/非公開チャンネルでのメッセージも閲覧できません。」

2023-01-12 01:34 UTC, kohkubo commented on backend/src/__tests__/users.service.spec.ts
> -import { ConfigService } from '@nestjs/config';
現状、このプルリクを通すために消す必要があるので消しました。修正依頼は行います！

2023-01-12 01:37 UTC, kohkubo commented on frontend/package.json
> -    "lint:style:fix": "stylelint --fix 'src/**/*.{css,less,sass,scss}'",
このコマンドを叩いたときにエラーが出ます。このエラーはコマンド自体が間違っていて起きているものなので、修正することができないエラーです。
YAGNI原則に従ってコードを書くべきだと考えています。

https://e-words.jp/w/YAGNI%E5%8E%9F%E5%89%87.html#:~:text=YAGNI%E5%8E%9F%E5%89%87%E3%80%90You%20Ain't,%E3%81%99%E3%81%B9%E3%81%8D%E3%81%A8%E3%81%99%E3%82%8B%E8%80%83%E3%81%88%E6%96%B9%E3%80%82

2023-01-12 01:48 UTC, kohkubo commented
> > ブラウザのキャッシュをクリアすると正しく動くかも！
> 
> キャッシュ消しても動かないかもです＞＜

node_modulesを消去して、
yarn cache clean
をして、
そのあと、ブラウザのcacheを消して実行してみてください！

2023-01-12 02:33 UTC, sunix2019 commented
以下が気になったので、コメントしておきます。
- OwnerじゃないユーザーでSettingsに入った場合に、Private等のボタンが表示される。
- Private等のボタンを一度押すと、状態が切り替わるけどページはそのまま。もう一度クリックでページ遷移する。

2023-01-12 02:36 UTC, Masaya-Kamei commented on frontend/package.json
> -    "lint:style:fix": "stylelint --fix 'src/**/*.{css,less,sass,scss}'",
css 類のファイルがないときのエラーなので、残しておいてもいいと思いました！

2023-01-12 03:32 UTC, kohkubo commented
> 追加で気になったのですが、レビュー項目に以下の文言がありました。現状、自分がブロックしていても、相手側はメッセージを送れてしまうので、ブロックを解除した場合、メッセージが受け取れてしまうと思いました。
> 
> 「ユーザーは、他のユーザーをブロックすることができます。**この場合、ブロックしたアカウントからのプライベートメッセージは受け取れませんし**、公開/非公開チャンネルでのメッセージも閲覧できません。」

詳しくありがとうございます！
これは内部実装に対してではなく、挙動についての要件だと思うので現状の仕様で問題ないと思います。

2023-01-12 03:33 UTC, kohkubo commented
> 以下が気になったので、コメントしておきます。
> 
> * OwnerじゃないユーザーでSettingsに入った場合に、Private等のボタンが表示される。
> * Private等のボタンを一度押すと、状態が切り替わるけどページはそのまま。もう一度クリックでページ遷移する。

直しました

2023-01-12 04:16 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoom/ChatRoomPage.tsx
>        socket.emit('leave_room_member', chatRoomId);
対応しました

2023-01-12 04:16 UTC, kohkubo commented on frontend/src/features/dm/routes/DmRoom.tsx
>                    id={message.id}
対応しました

2023-01-12 04:56 UTC, sunix2019 approved these changes
コメント出させてもらった部分の挙動確認しました！

ありがとうございました！

2023-01-12 05:13 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/index.tsx
> +      console.log(error);
このconsole.log 消していいと思いました！

2023-01-12 05:14 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/index.tsx
> +      console.log(isInvalidUrlError);
console.log 消していいと思いました！

2023-01-12 05:14 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/index.tsx
> +      console.log(error);
console.log 消していいと思いました！

2023-01-12 05:15 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/index.tsx
> +      console.log(isInvalidUrlError);
消していいと思いました！

2023-01-12 05:30 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/index.tsx
> +      console.log(isInvalidUrlError);
console.log 削除お願いします！

2023-01-12 05:31 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/index.tsx
> +      console.log(isInvalidUrlError);
削除おねがいします！

2023-01-12 05:32 UTC, kohkubo commented on frontend/src/features/dm/routes/index.tsx
> +      console.log(isInvalidUrlError);
消しました！

2023-01-12 05:33 UTC, kohkubo commented on frontend/src/features/chat/routes/index.tsx
> +      console.log(isInvalidUrlError);
消しました！

2023-01-12 05:48 UTC, Masaya-Kamei commented on frontend/src/features/dm/routes/DmRoomPage.tsx
>  import * as React from 'react';
ブロックしてるユーザーのDMに、直打ちでアクセスすると、DB ルーム入れるバグがありました。
再現手順
1. ２がdm を１に送る。
2. 1 が2 をブロック。
3. 1 が直打ちでDMページにアクセス。

2023-01-12 06:21 UTC, Masaya-Kamei approved these changes
一通り確認しました！
問題ないと思います。お疲れ様でした！！！

2023-01-12 06:53 UTC, merged