Chat6
yshima42/ft_transcendence pull request #366
Opened 2023-01-12 14:12 UTC by kohkubo

- 第三者がDMに入れる
- CHAT作成時の文字エラー
- CHATの周りの認可チェック

2023-01-12 14:49 UTC, kohkubo commented
早起きの方、どなたかレビューお願いします

2023-01-13 00:58 UTC, yshima42 requested changes

2023-01-13 00:58 UTC, yshima42 commented on frontend/src/features/chat/routes/CreateChatRoomsPage.tsx
>              />
![Screen Shot 2023-01-13 at 9 56 28](https://user-images.githubusercontent.com/87764458/212212645-7e0e704a-21ac-49b9-92ee-19f85a2ca05d.png)
Protectedでパスワードを設定しようとした後にPrivateルームを作ろうとするとエラー

2023-01-13 01:45 UTC, sunix2019 approved these changes
修正お疲れさまでした！しまさんの指摘部分以外は特に問題ないと思いました。
ありがとうございました！

2023-01-13 01:55 UTC, yshima42 approved these changes
ありがとうございます！

2023-01-13 01:55 UTC, merged