User account/frontend/profile complete
yshima42/ft_transcendence pull request #56
Opened 2022-11-23 02:49 UTC by Masaya-Kamei

2022-11-24 03:55 UTC, kohkubo requested changes

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/components/ProfileCardBase.tsx
> +export const ProfileCardBase: FC<PropsWithChildren> = memo((props) => {
ProfileCardsのほうがいい？Baseは継承元っぽい？
Board？
Wrapper的な名前のほうがいい？

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/routes/Profile.tsx
>  export const Profile: FC = memo(() => {
ここがドメイン知識を持つように設計したほうがよさそう

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/components/StatsCard.tsx
> +export const StatsCard: FC = memo(() => {
カード(分子)がドメイン知識を持たないほうがよい

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/hooks/useProfile.tsx
> +  if (user === undefined) {
実装の根拠が不明な場合はコメント等で残していただけるとありがたいです。

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/hooks/useProfile.tsx
> +    navigate('/', { replace: true });
navigateはいらないかも

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/routes/ProfileEdit.tsx
> +  const onFileInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
onClickイベントでとったほうがいいです

2022-11-24 03:55 UTC, kohkubo commented on frontend/src/features/profile/routes/ProfileEdit.tsx
> +        <input
fromタブじゃないでしょうか？

2022-11-25 03:25 UTC, Masaya-Kamei commented on frontend/src/features/profile/components/ProfileCardBase.tsx
> +export const ProfileCardBase: FC<PropsWithChildren> = memo((props) => {
Wrapper にしました！

2022-11-25 04:04 UTC, Masaya-Kamei commented on frontend/src/features/profile/routes/ProfileEdit.tsx
> +  const onFileInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
onClick でできそうになさそうになかったので、onChange のままでやりました。

2022-11-25 05:54 UTC, kohkubo approved these changes

2022-11-25 05:54 UTC, merged