MatchHistoryCardを作成しました。
yshima42/ft_transcendence pull request #59
Opened 2022-11-24 00:50 UTC by sunix2019

2022-11-24 04:44 UTC, kohkubo requested changes

2022-11-24 04:44 UTC, kohkubo commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +  const getMatches = useCallback(() => {
このCallBack関数は必要かどうかわからないので、調査が必要だと思います。

2022-11-24 04:44 UTC, kohkubo commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +      .catch(() => navigate('/', { replace: true }))
この処理をどうするのか話し合いましょう。ユーザーにエラーを通知する仕組みが必要そうです。

2022-11-24 04:44 UTC, kohkubo commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +      .finally(() => setLoading(false));
thenでいいかも？
catchは例外処理のときしか呼ばれないし

2022-11-24 04:44 UTC, kohkubo commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +    axios
プリズマの型が更新されていないようです

2022-11-25 04:05 UTC, sunix2019 commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +    axios
プリズマの型を更新したら解決しました！

2022-11-25 04:06 UTC, sunix2019 commented on frontend/src/features/profile/hooks/useAllMatches.tsx
> +      .finally(() => setLoading(false));
上記のcatchの部分を修正するときに、併せて修正したいと思います。

2022-11-25 04:45 UTC, kohkubo approved these changes

2022-11-25 04:45 UTC, merged