User account/backend/refactor
yshima42/ft_transcendence pull request #61
Opened 2022-11-24 05:44 UTC by hyoshie

2022-11-24 06:55 UTC, kohkubo requested changes

2022-11-24 06:55 UTC, kohkubo commented on backend/src/blocks/blocks.controller.ts
> +import {
未実装

2022-11-24 06:55 UTC, kohkubo commented on backend/src/blocks/blocks.service.ts
> +  async findBlockedUsers(id: string): Promise<User[]> {
Userの配列を返すエンドポイントはUserのモジュールが持っているほうが良さそうです。

2022-11-24 06:55 UTC, kohkubo commented on backend/src/blocks/blocks.service.spec.ts
> +  let service: BlocksService;
変数名はクラス名のキャメルケースにするのが良いと思います。

2022-11-24 06:55 UTC, kohkubo commented on backend/src/blocks/blocks.service.spec.ts
> +    const recordCountBefore = await prisma.block.count();
数で見るのではなく、モノ自体を確認すべき

2022-11-24 06:55 UTC, kohkubo commented on backend/src/friend-requests/friend-requests.service.ts
> +  async findIncomingRequest(id: string): Promise<User[]> {
Userのモジュールでやる

2022-11-25 05:38 UTC, yshima42 approved these changes

2022-11-25 05:51 UTC, merged