User account/backend/error case
yshima42/ft_transcendence pull request #66
Opened 2022-11-27 03:38 UTC by hyoshie

#54 
### やったこと
- ブロックAPIとフレンドAPIの異常系に対応しました
- ブロックAPIとフレンドAPIのテストをリファクタしました

2022-11-27 05:01 UTC, kohkubo requested changes

2022-11-27 05:01 UTC, kohkubo commented on backend/src/friend-requests/friend-requests.service.ts
> +  async removeTwo(
わかんないけど、カスケード使えるかも？

2022-11-27 06:21 UTC, hyoshie commented on backend/src/friend-requests/friend-requests.service.ts
> +  async removeTwo(
https://www.postgresql.jp/document/8.0/html/ddl-depend.html
今回の場合外部キー制約とは関係がないので使えなさそうです。

2022-11-28 02:58 UTC, yshima42 requested changes
英語の修正だけで細かいですが、修正した方が良いと思いました。

2022-11-28 02:58 UTC, yshima42 commented on backend/src/blocks/blocks.service.ts
> +      throw new BadRequestException('already blocks.');
You have already blocked this user.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/blocks/blocks.service.ts
> +      throw new NotFoundException('you did not block.');
You have not blocked this user.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/friend-requests/friend-requests.service.ts
> +      throw new BadRequestException('already sends a friend-request.');
You have already sent a friend-request to this user.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/friend-requests/friend-requests.service.ts
> +      throw new NotFoundException('you did not send a friend-request.');
You did not send a friend-request to this user.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/blocks/blocks.service.ts
> +      throw new BadRequestException('can not block myself.');
You cannot block yourself.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/friend-requests/friend-requests.service.ts
> +      throw new BadRequestException('can not send to myself.');
You cannot send a friend-request to yourself.

2022-11-28 02:58 UTC, yshima42 commented on backend/src/friend-requests/friend-requests.service.ts
> +      throw new NotFoundException('you are not friends.');
This user is not your friend.

2022-11-28 04:11 UTC, merged