2fa
yshima42/ft_transcendence pull request #76
Opened 2022-11-29 02:49 UTC by sunix2019

2022-12-02 05:37 UTC, yshima42 approved these changes
素晴らしい思います！

2022-12-02 08:16 UTC, Masaya-Kamei requested changes

2022-12-02 08:16 UTC, Masaya-Kamei commented on backend/src/auth/twoFactor/twoFactorAuth.controller.ts
> +import {
ここでディレクトリきって、controller とservice 作るのは、統一感ないかも。
auth controller, auth service に入れるか、
blocks みたいに、controller だけauth に入れて、service だけ用意するとかした方がいいと思います！

2022-12-02 08:16 UTC, Masaya-Kamei commented on backend/src/auth/twoFactor/twoFactorAuth.service.ts
> +  // TODO secret をハッシュ化させる。
ハッシュ化やっちゃいましょ。すぐ終わるので。
あと、User 返す時、secret は除いてください

2022-12-02 08:16 UTC, Masaya-Kamei commented on backend/src/auth/interfaces/signup-user.interface.ts
>  export type SignupUser = Omit<
これ、新規作成する時の型なので、
```suggestion
export type SignupUser = Omit<id, createAt, updatedAt, twoFactorAuthSecret>
```
でいいと思います！
auth.controller.tsの42ログインするとこ、nickname = name, onlineStatus=true, isTwoFactorAuthEnabled = false で修正お願いします。せきぐちさんと関係ないとこもありますが。

2022-12-04 00:49 UTC, sunix2019 commented on backend/prisma/schema.prisma
> +  twoFactorAuthSecret    String?
２要素認証がそもそもワンタイムパスワードのことを指してると考えられるし、
チュートリアルの命名もtwoFactorとなってたので、このままにします。

2022-12-04 01:10 UTC, sunix2019 commented on backend/src/users/users.service.ts
> +  async setTwoFactorAuthSecret(secret: string, id: string): Promise<User> {
update関数使うように修正しました。

2022-12-04 01:24 UTC, sunix2019 commented on backend/src/auth/twoFactor/twoFactorAuth.controller.ts
> +import {
authに移動させました。

2022-12-04 02:23 UTC, sunix2019 commented on backend/src/auth/interfaces/signup-user.interface.ts
>  export type SignupUser = Omit<
修正しました。

2022-12-04 02:54 UTC, sunix2019 commented on backend/src/auth/twoFactor/twoFactorAuth.service.ts
> +  // TODO secret をハッシュ化させる。
ハッシュ化は復号ができないので、やらないことにしました。

2022-12-04 03:03 UTC, Masaya-Kamei requested changes

2022-12-04 03:03 UTC, Masaya-Kamei commented on backend/src/users/users.service.ts
> +      if (attrs.includes('twoFactorAuthSecret')) {
これ、返さない方がいいと思います！

2022-12-04 06:37 UTC, Masaya-Kamei approved these changes
User 返す時に、secret 除く以外、問題ないと思います！
お疲れ様でした！

2022-12-04 06:37 UTC, merged