Chat
yshima42/ft_transcendence pull request #78
Opened 2022-11-29 07:42 UTC by kohkubo

2022-12-06 10:12 UTC, Masaya-Kamei requested changes
細かく確認させてもらいました。
勉強になりました。

2022-12-06 10:12 UTC, Masaya-Kamei commented on frontend/src/features/chat/hooks/useAllChats.ts
>  export const useAllChats = (): {
使ってないみたいなので、削除お願いします！

2022-12-08 02:27 UTC, kohkubo commented on frontend/src/features/chat/hooks/useAllChats.ts
>  export const useAllChats = (): {
消しました

2022-12-08 03:42 UTC, kohkubo commented on backend/src/chat/chat.controller.ts
> +@Controller('chat')
chat/messageとchat/roomに変更しました

2022-12-08 03:42 UTC, kohkubo commented on backend/src/chat/dto/update-chat.dto.ts
> +import { PartialType } from '@nestjs/swagger';
消しました

2022-12-08 03:44 UTC, kohkubo commented on backend/src/chat/chat.service.ts
> +    if (chatRoomId === undefined) {
消しました

2022-12-08 04:23 UTC, Masaya-Kamei approved these changes
機能的には問題ないので承認しました！
修正するかどうかお任せします。
リファクタリングで時間取りすぎるの良くないかなと思ったので。

2022-12-08 04:23 UTC, Masaya-Kamei commented on frontend/src/features/chat/routes/ChatRoom.tsx
> +import * as React from 'react';
このファイル名、DM と統一して欲しいと思いました！
ChatMessages.tsx にするか、
DirectMessages.tsxをDirectMessageRoom.tsx にする。

2022-12-08 04:23 UTC, Masaya-Kamei commented on backend/prisma/schema.prisma
> +model ChatUser {
前回指摘できず、申し訳ないです。
１つのチャットルームに所属するユーザーなので、ChatRoomUser or CharRoomMember でもいいと思いました。

2022-12-08 04:23 UTC, Masaya-Kamei commented on backend/prisma/schema.prisma
> +model DmUser {
ChatUser と同様。

2022-12-08 04:23 UTC, Masaya-Kamei commented on backend/prisma/schema.prisma
> +model Dm {
Dm をDirectMessage と省略せずに書くか、フロント合わせていただけると綺麗かなと思いました！

2022-12-08 04:23 UTC, Masaya-Kamei commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
エンドポイントは/でリソースを絞っていくと綺麗だと思いました。
これは僕の案なので、参考までに。
/chat-rooms/:chatRoomId
/chat-rooms/:chatRoomId/messages
( メッセージ取り消し /chat-rooms/:chatRoomId/messages/:messageId )
( ユーザーの情報(ステータス)変える /chat-rooms/:chatRoomId/users/:userId )

2022-12-08 04:36 UTC, kohkubo commented on backend/prisma/schema.prisma
> +model DmUser {
DmRoomUserに変更しました。

2022-12-08 04:36 UTC, kohkubo commented on frontend/src/features/chat/routes/ChatRoom.tsx
> +import * as React from 'react';
DirectMessageRoomにしました

2022-12-08 04:37 UTC, kohkubo commented on backend/prisma/schema.prisma
> +model Dm {
Dmと省略するのdefaultにしました

2022-12-08 04:41 UTC, kohkubo commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
Rest APIの本になるべく記号は使わずに階層で表現したほうがいいと書いていたのでそれに合わせました

2022-12-08 04:42 UTC, kohkubo commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
( メッセージ取り消し /chat-rooms/:chatRoomId/messages/:messageId )
( ユーザーの情報(ステータス)変える /chat-rooms/:chatRoomId/users/:userId )
このアイディアいいですね(^^)

2022-12-08 04:57 UTC, kohkubo commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
あー、絞るってそういうことか。
これは後でエンドポイントを増やすときに、見直してみます。

2022-12-08 05:21 UTC, Masaya-Kamei commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
リソースを絞っていくのは、よしえさんに教わりました。
了解です！

2022-12-08 05:26 UTC, Masaya-Kamei commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
フロントのurl のパスも同様に絞っていく感じでいいかもと思いました！

2022-12-08 05:31 UTC, merged

2022-12-08 05:31 UTC, Masaya-Kamei commented on backend/src/chat-message/chat-message.controller.ts
> +@Controller('chat/message')
記号は使わず、階層というのは、ページ教えていただけると有難いです。すぐわかれば